
<?php 
echo 'Welcome  '.AuthComponent::user('fullname'); 
?>		
<div class="row">
	<div class="col-lg-4">
	<h3>Total no of Tickets generated</h3>
	Total no of tickets = <?php echo $tickets; ?>
</div>
	<div class="col-lg-5">
	<h3>Total no of Tickets generated by you</h3>
	No of tickets generated by you = <?php echo $ticketuser; ?>
</div>
<div class="col-lg-3">
	<h3>Status of Tickets</h3>
<p>
Open Tickets= <?php echo $ticketopen; ?><br>
Closed Tickets= <?php echo $ticketclose; ?> </p>
</div>